[package]
name = "tearchan-example-ios"
version = "0.0.1"
edition = "2018"

[lib]
crate-type = ["lib", "staticlib"]

[dependencies]
common = { path = "../../common", features=["metal"] }

[build-dependencies]
cbindgen = "0.15.0"
