[package]
name = "web"
version = "0.0.1"
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.68"
wasm-logger = "0.2.0"
console_error_panic_hook = "0.1.6"
common = { path="../../common", features=["web"] }
